[package]
name = "bevy_streamline_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false, features = ["bevy_ui"] }

[dev-dependencies]
bevy = { version = "0.13.2", default-features = true }
bevy-inspector-egui = "0.23.3"
